### ISSUE TITLE
A possible bug (or a misunderstanding of the API)

### ISSUE THREAD

**Issue by SyFlo** [mg901/styled-breakpoints#1119]
I just started using this lib and I'm a little bit confused by the API. The docs give two examples with the `md` breakpoint and the `up` and `down` functions respectively. The first example seems clear to me: `${up('md')}` translates to `@media (min-width: 768px)`. But in the second example, `${down('md')}` translates to `@media (max-width: 991.98px)` whereas I would have expected `@media (max-width: 767.98px)` (also see the screenshot below).
On a given viewport width of 800px, both `useBreakpoint(up('md'))` and `useBreakpoint(down('md'))` return true at the same time. Maybe I'm understanding the API wrong, but shouldn't they be mutually exclusive? I'd expect the latter to be false.
Merry Christmas and thank you in advance for your help 🙏

![image](https://user-images.githubusercontent.com/68643437/147251755-73352c2d-858d-40d5-8c62-d07d0b774063.png)

**Comment by mg901** [comment]
@SyFlo yes, you really don't understand how down works. Let's define the range for md - from 768px to 991.98px. Next, lg starts from 992px to 1199.98px. If you are designing a mobile-first layout you want the minimum values. If from largest to smallest (desktop first) you use the maximum values. Try to carefully study [this example](https://codesandbox.io/s/desktop-first-example-0plsg?fontsize=14&hidenavigation=1&module=/src/app.tsx&theme=dark&file=/src/app.tsx), it clearly shows what values you are working with.

**Comment by mg901** [comment]
@SyFlo Hey bro, thank you for your kind words and Merry Christmas greetings. Can you please tell me from the answer that helped you understand how to use styled-breakpoints?

**Comment by SyFlo** [comment]
@mg901 Thank you for your answer and sorry for the delay, I've been away from keyboard over the last few days. Sure, I can work with that.

**Comment by pierreburel** [comment]
Hey, i'm afraid i have to agree with @SyFlo: the API for `down` feels weird, especially since it's not how Bootstrap works.

bootstrap:

`@include media-breakpoint-down(md)` = `@media (max-width: 767.98px)` (= `down("sm")`)
`@include media-breakpoint-up(md)` = `@media (min-width: 768px)`

styled-breakpoints:

`down("md")` = `@media (max-width: 991.98px)` (= `@include media-breakpoint-down(lg)`)
`up("md")` = `@media (min-width: 768px)`

Here's a (crude) demo showing the differences: https://codesandbox.io/s/angry-boyd-vfn1k

There's also a difference with `between`.
 
bootstrap: `@include media-breakpoint-between(sm, md)` = `@media (min-width: 576px) and (max-width: 767.98px)`  
styled-breakpoints: `between("sm", "md")` = `@media (min-width: 576px) and (max-width: 991.98px)`

But tbh i don't really know how you could possibly align with Bootstrap without breaking changes… or maybe by providing alternative `downInclusive` and `betweenExclusive` methods (sorry i'm not good at naming things)?

**Comment by mg901** [comment]
@pierreburel , @SyFlo see changes in [release](https://github.com/mg901/styled-breakpoints/releases/tag/v11.0.0)

**Comment by SyFlo** [comment]
@mg901 awesome, I'll check it out
