### ISSUE TITLE
Types are incorrect and/or missing

### ISSUE THREAD

**Issue by daviddelusenet** [mg901/styled-breakpoints#1390]
First of all, thanks for maintaining this library! One of the few that hasn't been left for death.

However, I've been running into some issues when using this package in a TypeScript project.

First of all, the `up`/`down`/`between`/`only` function parameter is not strictly typed. It would be nice if the keys from the `createTheme` object would be used here. Now this parameter is just of type `string`. However, I can still use the package fine without this strict typing.

Another thing which is causing a bigger issue: the return value of the `up`/`down`/`between`/`only` functions. At the moment that is `any`, which causes an error when using these functions in combination with `useBreakpoint`:

```tsx
const isDesktop = useBreakpoint(up("lg"));

// The following ESLint error is being thrown:
// Unsafe argument of type `any` assigned to a parameter of type `Function`.
```

Let me know if you need any more information!

**Comment by mg901** [comment]
@daviddelusenet Thank you for your question and interest for Styled Breakpoints, and I'm sorry for my tooooo long answer. Unfortunately, At the moment I don't have enough time to give full answers. Due to the fact that Russia attacked Ukraine. I, as a citizen of Russia who does not support this barbarity, decided to leave my home. Now all my time is spent on learning more English and solving algorithmic problems. I urgently need to find a country where I can feel safe and think about the future.


If you would to help me with this problem, you can share me examples, for example, on codesandbox. I will definitely look into this problem as soon as I find a little more time.
